sudo: false

language: php

# Only build the main develop/master branches - feature branches will be covered by PRs
branches:
  only:
    - /^[0-9\.]+\/(develop|master)$/

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.3
      env: 'COMPOSER_PHPUNIT="lowest"'

before_script:
  - composer self-update
  - COMPOSER_ROOT_VERSION=3.3.x-dev composer install --prefer-dist --no-interaction
  - if [ "$COMPOSER_PHPUNIT" = "lowest" ]; then COMPOSER_ROOT_VERSION=3.3.x-dev composer update --prefer-lowest --with-dependencies phpunit/phpunit; fi;
  - vendor/bin/koharness

script:
  - cd /tmp/koharness && ./vendor/bin/phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  email: false
