language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-dist
  - vendor/bin/koharness

script:
  - cd /tmp/koharness && ./vendor/bin/phpunit --bootstrap=modules/unittest/bootstrap.php modules/unittest/tests.php

notifications:
  irc:
    channels:
      - "irc.freenode.org#kohana"
    template:
      - "%{repository}/%{branch} (%{commit}) - %{author}: %{message}"
      - "Build details: %{build_url}"
  email: false
